/**
 * ページコンテンツ生成モジュール（サンプルデータ完全版）
 */

const pages = {
    dashboard: async () => {
        const total = SAMPLE_TICKETS.length;
        const newTickets = SAMPLE_TICKETS.filter(t => t.status === 'New').length;
        const inProgress = SAMPLE_TICKETS.filter(t => t.status === 'In Progress').length;
        const resolved = SAMPLE_TICKETS.filter(t => t.status === 'Resolved').length;
        const aiProcessed = SAMPLE_TICKETS.filter(t => t.ai_processed).length;

        return `
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-label">全チケット</div>
                    <div class="stat-value" style="color: var(--primary);">${total}</div>
                    <div class="stat-trend">📈 前週比 +12%</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">新規</div>
                    <div class="stat-value" style="color: var(--warning);">${newTickets}</div>
                    <div class="stat-trend">🔥 対応待ち</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">対応中</div>
                    <div class="stat-value" style="color: #722ed1;">${inProgress}</div>
                    <div class="stat-trend">⚡ 処理中</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">解決済み</div>
                    <div class="stat-value" style="color: var(--success);">${resolved}</div>
                    <div class="stat-trend">✅ 完了</div>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">🤖 マルチAI統計</h3>
                </div>
                <div class="stats-grid" style="grid-template-columns: repeat(3, 1fr);">
                    <div class="stat-card" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white;">
                        <div class="stat-label" style="color: rgba(255,255,255,0.9);">AI処理済みチケット</div>
                        <div class="stat-value">${aiProcessed}</div>
                        <div class="stat-trend" style="color: rgba(255,255,255,0.9);">📊 総チケットの${AI_STATS.aiProcessingRate}%</div>
                    </div>
                    <div class="stat-card" style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white;">
                        <div class="stat-label" style="color: rgba(255,255,255,0.9);">AI自動生成ナレッジ</div>
                        <div class="stat-value">${AI_STATS.autoGeneratedKnowledge}</div>
                        <div class="stat-trend" style="color: rgba(255,255,255,0.9);">✨ 品質スコア平均 ${AI_STATS.averageQualityScore}%</div>
                    </div>
                    <div class="stat-card" style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); color: white;">
                        <div class="stat-label" style="color: rgba(255,255,255,0.9);">自動化成功率</div>
                        <div class="stat-value">${AI_STATS.automationSuccessRate}%</div>
                        <div class="stat-trend" style="color: rgba(255,255,255,0.9);">🎯 平均処理: ${AI_STATS.averageProcessingTime}秒</div>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">最近のチケット</h3>
                    <button class="btn btn-primary" onclick="navigateTo('tickets')">すべて表示</button>
                </div>
                <div class="table-container">
                    <table>
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>種別</th>
                                <th>件名</th>
                                <th>優先度</th>
                                <th>ステータス</th>
                                <th>ITSM</th>
                                <th>AI</th>
                                <th>作成</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${SAMPLE_TICKETS.slice(0, 10).map(ticket => `
                                <tr onclick="viewTicket('${ticket.ticket_id}')">
                                    <td>#${ticket.ticket_number}</td>
                                    <td>${ticket.type === 'incident' ? '🚨' : ticket.type === 'service_request' ? '📋' : '🔄'}</td>
                                    <td style="max-width: 250px; overflow: hidden; text-overflow: ellipsis;">${ticket.subject}</td>
                                    <td><span class="tag tag-${ticket.priority.toLowerCase()}">${ticket.priority}</span></td>
                                    <td><span class="tag tag-${ticket.status.toLowerCase().replace(/ /g, '-')}">${ticket.status}</span></td>
                                    <td><span class="tag">${ITSM_TYPES[ticket.itsm_type].icon}</span></td>
                                    <td>${ticket.ai_processed ? '🤖' : '-'}</td>
                                    <td style="font-size: 12px;">${new Date(ticket.created_at).toLocaleString('ja-JP', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</td>
                                </tr>
                            `).join('')}
                        </tbody>
                    </table>
                </div>
            </div>

            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 24px;">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">📊 ITSM分類統計</h3>
                    </div>
                    <div style="display: flex; flex-direction: column; gap: 12px;">
                        ${Object.entries(ITSM_TYPES).map(([key, type]) => {
                            const count = SAMPLE_TICKETS.filter(t => t.itsm_type === key).length;
                            const percentage = Math.round((count / total) * 100);
                            return `
                                <div style="display: flex; align-items: center; gap: 12px;">
                                    <span style="font-size: 24px;">${type.icon}</span>
                                    <div style="flex: 1;">
                                        <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">
                                            <span style="font-weight: 600;">${type.label}</span>
                                            <span style="color: var(--gray-500);">${count}件 (${percentage}%)</span>
                                        </div>
                                        <div style="background: var(--gray-200); height: 8px; border-radius: 4px; overflow: hidden;">
                                            <div style="background: var(--primary); height: 100%; width: ${percentage}%; transition: width 0.3s;"></div>
                                        </div>
                                    </div>
                                </div>
                            `;
                        }).join('')}
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">🎯 品質保証Hooks</h3>
                    </div>
                    <div class="timeline">
                        ${HOOKS_LOGS.map(hook => `
                            <div class="timeline-item completed">
                                <div class="timeline-content">
                                    <div class="timeline-title">✅ ${hook.hook}</div>
                                    <div class="timeline-desc">${hook.result}</div>
                                    <div class="timeline-time">${hook.duration}秒</div>
                                </div>
                            </div>
                        `).join('')}
                    </div>
                </div>
            </div>
        `;
    },

    // その他のページは省略形で定義
    'ai-assistant': () => pages_aiAssistant(),
    tickets: async () => pages_tickets(),
    'ai-knowledge': async () => pages_aiKnowledge(),
    knowledge: async () => pages_knowledge(),
    approvals: async () => pages_approvals(),
    m365: () => pages_m365(),
};
